### ISSUE TITLE
Issues with `@component` expansion and `component_id`

### ISSUE THREAD

**Issue by c42f** [louisponet/Overseer.jl#3]
Bringing over a discussion from discourse, where @louisponet wrote:

> Currently the Components are accessed with the type of their ComponentData, i.e. `m[Spring]` as in the README. Early on I decided to put components inside as array in the `Ledger` , and generate the index at parse/compile time with the `@component` macro. This leads to good performance, and I like the ease of use. However, one problem arises when using `Overseer.jl` in a module, that itself uses a package that also uses Overseer, and one would want to create a ledger that holds components from both packages.
>
> Currently, Overseer defines a [COMPONENTDATA_TYPES](https://github.com/louisponet/Overseer.jl/blob/820a3426e59311ddbb2604845cf2ea64290f0f1c/src/component.jl#L276) array in the module that it’s called from, and the workaround I’ve used is to copy the one from the lower package into the top level module upon initialization, so the indices of the new components get added to the old ones. Aside from being quite clunky, I’m not even sure if this workaround would work when using two packages that each use Overseer.
>
> One way around this would be to use a Tuple in each Ledger instead of an array and generate the `getindex` function each time. This is less flexible, I guess mainly during development when you’d like to add stages interactively. Maybe this is not such an issue and is really the way forward.

**Comment by c42f** [comment]
> Aside from being quite clunky, I’m not even sure if this workaround would work when using two packages that each use Overseer.

@louisponet You're correct about that. There's inherently no way to for the two separate packages to statically agree on disjoint `component_id`s if they're precompiled separately, because they're each precompiled independently.

That means there needs to be some runtime component to this. There's certainly several options, though they will have other tradeoffs.

> One way around this would be to use a Tuple in each Ledger instead of an array and generate the getindex function each time.

I don't really understand this.  Do you mean making `Ledger` parametric on the component types?

```julia
mutable struct Ledger{ComponentTuple} <: AbstractLedger
    ...
    components::ComponentTuple
end
```

This is certainly one option and it'd allow the compiler to generate the most efficient code for `getindex(m::AbstractLedger, ::Type{<:ComponentData})`.  You wouldn't be able to dynamically add components to the ledger though.

**Comment by c42f** [comment]
Another issue I noticed with the way `@component` currently works is that the macro expansion itself has side effects. This means if you call `@macroexpand @component ...` multiple times without evaluating the code, the second macro expansion doesn't do anything. This can be avoided by emitting the code to check COMPONENT_DATA as part of the macro output.

**Comment by louisponet** [comment]
> Do you mean making Ledger parametric on the component types?

Yes, exactly.
Pros are that it does away with the need for the `Stub` components ugliness, and gets around the issue of the COMPONENT_DATA. 
Con is that indeed it doesn't allow for the dynamic adding. 
On the latter, I've found that usually for me this is important during development, but not so much while "running" the eventual program. 

With that in mind, I was thinking to have 2 types of Ledger, one which is really dynamic, i.e. just does something like a `findfirst` to find the component with the right type in the array, or works with a `Dict{DataType, Component}`. Then a second Ledger would take the first as the input, i.e. when you're satisfied you have what you need and want speed, and works using a `Tuple`. 
Maybe it's not the most elegant solution though.

I will have a look at what causes your second comment.

**Comment by c42f** [comment]
> Then a second Ledger would take the first as the input, i.e. when you're satisfied you have what you need and want speed, and works using a Tuple. Maybe it's not the most elegant solution though.

This actually sounds perfectly reasonable to me and I think it'll be neater 

> I will have a look at what causes your second comment.

Well, it's no major problem for me in practice, just an oddity/slight wart that the macro has side effects like this. The reason is the lines here:

https://github.com/louisponet/Overseer.jl/blob/820a3426e59311ddbb2604845cf2ea64290f0f1c/src/component.jl#L280-L281

**Comment by c42f** [comment]
> This actually sounds perfectly reasonable to me and I think it'll be neater.

Actually I realized that was ambiguous. I think the Tuple idea is quite reasonable and neat. Not sure you need the dynamic ledger, another way to get something maybe-similar would be to have `push(ledger, stage, system)` return a new wider ledger with the extra components rather than the mutating `push!`. Might be inconvenient though - depends on your use case.

It occurs to me that there is a way to keep the current system at the cost of one extra indirection in getindex. It looks like

```julia
@component struct X
    x::Int
end
```

producing

```julia
struct X <: ComponentData
    x::Int
end

const _X_id = Ref(0)
_package_id_registry[X] = _X_id

Overseer.component_id(::Type{X}) = _X_id[]

Overseer.component_type(::Type{X}) = Overseer.Component
```

Some extra code would then be needed during package `__init__()` to dynamically initialize every component id from a global counter (but at package init time, rather than precompile-time). Unitful.jl has something slightly similar to register units from unit extension modules.

The cost of this is an extra indirection inside `component_id`, so the compiler would no longer be able to hard code the id of components into the assembly code. However this should be very minimal if systems generally loop over many entities (is speed of component access even an actual problem?) Also a little extra work for users of Overseer to add the right code to `__init__`.

**Comment by c42f** [comment]
> is speed of component access even an actual problem

Last thought for the night - are you sure using the `Dict`-based solution is actually a performance problem? It's probably only computing `hash(objectid(X))` for the hash of the type which is likely very fast, followed by a single-indirection for the hash table lookup.

**Comment by louisponet** [comment]
Yea these are good points, it only really matters when someone does something inside inner loops to update a component by calling it directly as `m[CData][e]=...`, which there's no reason to really try to get fast anyway. 
I'll try the Dict and your other solution out and see how it affects (or doesn't) the timing of Glimpse.

**Comment by louisponet** [comment]
I ran some tests and benchmarks with the Dict_ledger branch and found that using a Dict has really very little impact on most things. I think this is probably the way to go, minimal changes, full retaining of the flexibility. If it really does become critical at a certain point we can still go with the conversion to a Tuple ledger at runtime or something, at a later stage. 

If you agree I think I will merge it in and close this issue for now.

**Comment by louisponet** [comment]
Come to think of it, I think that even means that component structs can now also have type parameters. I seem to remember that was due to some implementation detail with the `component_id` machinery.

**Comment by c42f** [comment]
Sounds good to me, in the past I've been surprised by just how fast `Dict` is. As you say, components are unlikely to be looked up inside an inner loop — at least in the way I've been using it, they're only looked ~once per system update for each system.
